apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender
  namespace: default
  labels:
    app: recommender
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recommender
  template:
    metadata:
      labels:
        app: recommender
    spec:
      containers:
        - name: nginx
          image: mcr.microsoft.com/oss/nginx/nginx:1.25.4
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "4000m"
              memory: "10Gi"
            limits:
              cpu: "4000m"
              memory: "10Gi"
