apiVersion: v1
kind: Service
metadata:
  name: shop
  namespace: default
spec:
  selector:
    app: shop-v1
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
